id: P008250
initial_creation_type: ocr
source_metadata:
  id: bdr:W30037
  title: གསུང་ཐོར་བུ། པདྨ་བཛྲ།
  author: ''
  volumes:
    fee9b4241eb145f5b46ec399f86dfaf4:
      image_group_id: I1KG12943
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
